const appConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  GET_LIST_PRODUCT_REQUEST: 'GET_LIST_PRODUCT_REQUEST',
  GET_LIST_PRODUCT_SUCCESS: 'GET_LIST_PRODUCT_SUCCESS',
  GET_LIST_PRODUCT_FAILED: 'GET_LIST_PRODUCT_FAILED',
  ADD_WISHLIST: 'ADD_WISHLIST',
  ADD_CART: 'ADD_CART'
}

export default appConstants
